-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.student
(
    student_id integer NOT NULL,
    parents_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    birth_date date NOT NULL,
    class character varying(20) NOT NULL,
    email character varying(100) NOT NULL,
    CONSTRAINT "Student_pkey" PRIMARY KEY (student_id)
);

CREATE TABLE IF NOT EXISTS public.teacher
(
    teacher_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    CONSTRAINT "Teacher_pkey" PRIMARY KEY (teacher_id)
);

CREATE TABLE IF NOT EXISTS public.parents
(
    parents_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone character varying(30) NOT NULL,
    email character varying(100) NOT NULL,
    CONSTRAINT "Parents_pkey" PRIMARY KEY (parents_id)
);

CREATE TABLE IF NOT EXISTS public.subject
(
    subject_id integer NOT NULL,
    name character varying(50) NOT NULL,
    CONSTRAINT "Subject_pkey" PRIMARY KEY (subject_id)
);

CREATE TABLE IF NOT EXISTS public.journal
(
    journal_id integer NOT NULL,
    student_id integer NOT NULL,
    teacher_id integer NOT NULL,
    subject_id integer NOT NULL,
    entry_date date NOT NULL,
    grade integer,
    attendance_status character varying(30) NOT NULL,
    CONSTRAINT "Journal_pkey" PRIMARY KEY (journal_id)
);

ALTER TABLE IF EXISTS public.student
    ADD FOREIGN KEY (parents_id)
    REFERENCES public.parents (parents_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.journal
    ADD FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.journal
    ADD FOREIGN KEY (teacher_id)
    REFERENCES public.teacher (teacher_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.journal
    ADD FOREIGN KEY (subject_id)
    REFERENCES public.subject (subject_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;